object Version {
    const val appCompat = "1.4.2"
    const val coil = "2.1.0"
    const val constraintLayout = "2.1.4"
    const val coreKtx = "1.8.0"
    const val espressoCore = "3.4.0"
    const val extJunit = "1.1.3"
    const val kotlin = "1.6.21"
    const val gradle = "7.2.1"
    const val junit = "4.13.2"
    const val lifecycle = "2.5.1"
    const val navigation = "2.5.1"
    const val retrofit = "2.9.0"
    const val loggingInterceptor = "4.10.0"
    const val moshi = "1.13.0"
    const val room = "2.4.3"
    const val hilt = "2.38.1"
    const val dataStore = "1.0.0-alpha02"
    const val ktlint = "10.3.0"
    const val detekt = "1.21.0"
    const val versionUpdates = "0.29.0"
}