object Version {
    const val appCompat = "1.3.1"
    const val coil = "1.3.2"
    const val constraintLayout = "2.1.0"
    const val coreKtx = "1.6.0"
    const val espressoCore = "3.4.0"
    const val extJunit = "1.1.3"
    const val kotlin = "1.4.32"
    const val gradle = "4.1.2"
    const val junit = "4.13.2"
    const val lifecycle = "2.3.1"
    const val navigation = "2.3.5"
    const val retrofit = "2.9.0"
    const val gson = "2.9.0"
    const val room = "2.3.0"
    const val hilt = "2.37"
    const val dataStore = "1.0.0-alpha02"
}